# Generated by Django 5.2.17 on 2026-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_daily_quota', models.PositiveIntegerField(blank=True, help_text='Analyses par utilisateur sur 24 h. Vide = valeur du .env, 0 = illimité.', null=True)),
                ('force_mock_ai', models.BooleanField(default=False, help_text='Force le moteur démo même si une clé API est configurée (économise les crédits).')),
                ('allow_registration', models.BooleanField(default=True)),
                ('announcement', models.CharField(blank=True, default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
